-- 配置表
CREATE TABLE IF NOT EXISTS base_config (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL,
  password TEXT NOT NULL,
  bot_token TEXT DEFAULT NULL,
  chat_id TEXT NOT NULL,
  bound_user_name TEXT DEFAULT NULL,
  bound_user_username TEXT DEFAULT NULL,
  stop_push INTEGER DEFAULT 0,
  only_title INTEGER DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- psots 表
CREATE TABLE IF NOT EXISTS posts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  post_id INTEGER NOT NULL,
  title TEXT NOT NULL,
  memo TEXT NOT NULL,
  category TEXT NOT NULL,
  creator TEXT NOT NULL,
  push_status INTEGER DEFAULT 0,
  sub_id INTEGER DEFAULT NULL,
  pub_date DATETIME NOT NULL,
  push_date DATETIME DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_posts_post_id ON posts(post_id);

-- keywords_sub 表
CREATE TABLE IF NOT EXISTS keywords_sub (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  keyword1 TEXT DEFAULT NULL,
  keyword2 TEXT DEFAULT NULL,
  keyword3 TEXT DEFAULT NULL,
  creator TEXT NULL,
  category TEXT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

